"""PEP 517/660 wrapper that stages canonical noema-core for reviewer builds.

The reviewer cannot declare an immutable external ``noema-core`` dependency until
that package is published. Distribution builds therefore stage one canonical
monorepo snapshot into a build-only directory before delegating to setuptools;
source distributions embed that snapshot so they remain self-contained.
Editable installs instead keep an ignored link to the canonical source when the
platform permits it, preserving editable semantics without making the generated
staging path a second source of truth.
"""

from __future__ import annotations

from pathlib import Path
from shutil import copytree, rmtree
from typing import Any, Callable, TypeVar

from setuptools import build_meta as _setuptools

_PROJECT_ROOT = Path(__file__).resolve().parent
_CANONICAL_CORE = _PROJECT_ROOT.parent / "packages" / "noema-core" / "src" / "noema_core"
_STAGING_ROOT = _PROJECT_ROOT / "_build_include"
_STAGED_CORE = _STAGING_ROOT / "noema_core"
_BuildResult = TypeVar("_BuildResult")


def _reset_staging_root() -> None:
    """Remove generated package staging before publishing a new canonical view."""

    if _STAGING_ROOT.exists() or _STAGING_ROOT.is_symlink():
        rmtree(_STAGING_ROOT)
    _STAGING_ROOT.mkdir(parents=True)


def _prepare_core() -> bool:
    """Ensure distribution packaging reads one exact canonical source snapshot.

    A monorepo checkout recreates staging from the canonical source so stale
    generated files cannot become package authority. An extracted source
    distribution has no sibling package checkout and consumes the staged
    snapshot embedded by the source-distribution build.
    """

    if _CANONICAL_CORE.is_dir():
        _reset_staging_root()
        copytree(_CANONICAL_CORE, _STAGED_CORE)
        return True
    if _STAGED_CORE.is_dir():
        return False
    raise RuntimeError("canonical noema-core source is unavailable for reviewer packaging")


def _prepare_editable_core() -> None:
    """Expose canonical noema-core to an editable install without a stale copy.

    The editable finder generated by setuptools references ``_build_include``.
    On platforms that support directory symlinks, that path points directly at
    the canonical monorepo source and therefore follows edits. If the platform
    refuses directory symlinks, a generated copy is used as a portability
    fallback; rerunning the editable install refreshes it from canonical source.
    Extracted sdists already contain their bounded staged snapshot.
    """

    if _CANONICAL_CORE.is_dir():
        _reset_staging_root()
        try:
            _STAGED_CORE.symlink_to(_CANONICAL_CORE, target_is_directory=True)
        except OSError:
            copytree(_CANONICAL_CORE, _STAGED_CORE)
        return
    if _STAGED_CORE.is_dir():
        return
    raise RuntimeError("canonical noema-core source is unavailable for reviewer editable install")


def _with_core_staging(
    builder: Callable[..., _BuildResult],
    *args: Any,
    **kwargs: Any,
) -> _BuildResult:
    """Delegate a distribution hook and clean repository-only staging afterward."""

    created = _prepare_core()
    try:
        return builder(*args, **kwargs)
    finally:
        if created and _STAGING_ROOT.exists():
            rmtree(_STAGING_ROOT)


def _with_editable_core(
    builder: Callable[..., _BuildResult],
    *args: Any,
    **kwargs: Any,
) -> _BuildResult:
    """Delegate an editable hook while retaining its ignored canonical source view."""

    _prepare_editable_core()
    return builder(*args, **kwargs)


def build_wheel(
    wheel_directory: str,
    config_settings: dict[str, Any] | None = None,
    metadata_directory: str | None = None,
) -> str:
    """Build a reviewer wheel containing the staged canonical noema-core snapshot."""

    return _with_core_staging(
        _setuptools.build_wheel,
        wheel_directory,
        config_settings,
        metadata_directory,
    )


def build_editable(
    wheel_directory: str,
    config_settings: dict[str, Any] | None = None,
    metadata_directory: str | None = None,
) -> str:
    """Build an editable reviewer wheel against the canonical shared-core source."""

    return _with_editable_core(
        _setuptools.build_editable,
        wheel_directory,
        config_settings,
        metadata_directory,
    )


def build_sdist(
    sdist_directory: str,
    config_settings: dict[str, Any] | None = None,
) -> str:
    """Build a self-contained source distribution from canonical monorepo source."""

    return _with_core_staging(_setuptools.build_sdist, sdist_directory, config_settings)


def prepare_metadata_for_build_wheel(
    metadata_directory: str,
    config_settings: dict[str, Any] | None = None,
) -> str:
    """Prepare wheel metadata under the same package-discovery boundary as builds."""

    return _with_core_staging(
        _setuptools.prepare_metadata_for_build_wheel,
        metadata_directory,
        config_settings,
    )


def prepare_metadata_for_build_editable(
    metadata_directory: str,
    config_settings: dict[str, Any] | None = None,
) -> str:
    """Prepare editable metadata against the canonical shared-core source view."""

    return _with_editable_core(
        _setuptools.prepare_metadata_for_build_editable,
        metadata_directory,
        config_settings,
    )


def get_requires_for_build_wheel(
    config_settings: dict[str, Any] | None = None,
) -> list[str]:
    """Return wheel-build requirements after validating package-source availability."""

    return _with_core_staging(_setuptools.get_requires_for_build_wheel, config_settings)


def get_requires_for_build_editable(
    config_settings: dict[str, Any] | None = None,
) -> list[str]:
    """Return editable requirements after validating canonical package availability."""

    return _with_editable_core(_setuptools.get_requires_for_build_editable, config_settings)


def get_requires_for_build_sdist(
    config_settings: dict[str, Any] | None = None,
) -> list[str]:
    """Return sdist-build requirements after validating package-source availability."""

    return _with_core_staging(_setuptools.get_requires_for_build_sdist, config_settings)
